// The below used with forms and saving them. 
export const SAVE_FORM_DATA = "SAVE_FORM_DATA_TO_STORE";
export const SAVE_FORM_ERROR = "SAVE_FORM_ERROR_TO_STORE";

// The below handles the popUp actions
export const TOGGLE_POPUP_ON_SIGNUP = "TOGGLE_POPUP_SIGNUP_ON_TO_STORE"
export const TOGGLE_POPUP_OFF_SIGNUP = "TOGGLE_POPUP_SIGNUP_OFF_TO_STORE"
export const TOGGLE_POPUP_ON_LOGIN = "TOGGLE_POPUP_LOGIN_ON_TO_STORE"
export const TOGGLE_POPUP_OFF_LOGIN = "TOGGLE_POPUP_LOGIN_OFF_TO_STORE"

// The below is for User Actions
export const SAVE_CURRENT_USER = "SET_CURRENT_USER_TO_STORE"

// The below is for Post Actions
export const SAVE_POST_DATA = "SAVE_POST_DATA_TO_STORE"
export const SAVE_LATEST_POST_DATA = "SAVE_LATEST_POST_DATA_TO_STORE"
export const SAVE_ALL_POSTS_DATA = "SAVE_ALL_POSTS_DATA_TO_STORE"
export const ADD_POST_TO_ALL_POSTS = "ADD_POST_TO_ALL_POSTS"
export const SAVE_FILTERED_POSTS_DATA = "SAVE_FILTERED_POSTS_DATA"